spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl_auto: create #애플리케이션 실행 시점에 테이블을 drop하고 재생성
    properties:
      hibernate:
#        show_sql: true #System.out에 하이버네이트 실행 SQL 남김
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남김(추천 방법)
    org.hibernate.orm.jdbc.bind: trace
